on:
  push:
    paths-ignore:
      - 'cli-version'


name: Deploy to s3

jobs:
  test:
    name: Deploy to s3
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          include:
            - os: ubuntu-latest
              extension: ""
              filepath: "ubuntu"

            - os: macos-latest
              extension: ""
              filepath: "mac"

            - os: windows-latest
              extension: ".exe"
              filepath: "windows"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Version
        run: echo "::set-env name=CLI_VERSION::$(cat cli-version)"

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Rename Binary
        run: |
          cp target/release/activity-insights activity-insights-$CLI_VERSION${{ matrix.extension }}
          cp target/release/activity-insights activity-insights-latest${{ matrix.extension }}
          pwd
          ls -al
          aws s3 sync . s3://ps-cdn/learner-workflow/ps-time-test/${{ matrix.filepath }} --exclude="*" --include="activity-insights-$CLI_VERSION${{ matrix.extension }}"
        shell: bash
        env:
         AWS_REGION: 'us-west-2'
         S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
