on:
  push:
    branches: 
      - master
    paths:
    - 'cli-version'


name: Deploy to s3

jobs:
  test:
    name: Deploy to s3
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          include:
            - os: ubuntu-latest
              extension: ""

            - os: macos-latest
              extension: ""

            - os: windows-latest
              extension: ".exe"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Version
        run: echo "::set-env name=CLI_VERSION::$(cat cli-version)"

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Rename Binary
        run: |
          cp target/release/activity-insights activity-insights-$CLI_VERSION${{ matrix.extension }}
          cp target/release/activity-insights activity-insights-latest${{ matrix.extension }}
        shell: bash
      
